<a href="https://colab.research.google.com/github/DavProg49/Notebook/blob/main/numpy_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy exemple :

In [ ]:
import numpy as np

# Tableau d'entiers:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
# tableau de flottant (spécification du type)
np.array([1, 2, 3, 4], dtype='float32')


array([1., 2., 3., 4.], dtype=float32)

In [ ]:
# Une liste de listes est transformée en un tableau multi-dimensionnel
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# Un tableau de longueur 10, rempli d'entiers qui valent 0
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Un tableau de taille 3x5 rempli de nombres à virgule flottante de valeur 1
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Un tableau 3x5 rempli de 3,14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# Un tableau rempli d'une séquence linéaire
# commençant à 0 et qui se termine à 20, avec un pas de 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Un tableau de 5 valeurs, espacées uniformément entre 0 et 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Celle-ci vous la conaissez déjà! Essayez aussi "randint" et "normal"
np.random.random((3, 3))

array([[0.32659512, 0.54283938, 0.72265218],
       [0.1737472 , 0.39012091, 0.07996026],
       [0.70475421, 0.15479466, 0.13257447]])

In [ ]:
# La matrice identité de taille 3x3 
# (matrice identité : https://fr.wikipedia.org/wiki/Matrice_identit%C3%A9)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int64


In [ ]:
#Accéder à un élément :
print(x1)

# Pour accéder au premier élément
print(x1[0])

# Pour accéder au dernier élément
print(x1[-1])

[5 0 3 3 7 9]
5
9


In [ ]:
x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
print(x2[0,1])

5


In [ ]:
# On peut aussi modifier les valeurs
x1[1] = "1000"
print(x1)

[   5 1000    3    3    7    9]


In [ ]:
# Attention au type
x1[1] = 3.14
print(x1)

[5 3 3 3 7 9]


In [ ]:
print(x1[:5])  # Les cinq premiers éléments

print(x1[5:])  # Les éléments à partir de l'index 5

print(x1[::2])  # Un élément sur deux

[5 3 3 3 7]
[9]
[5 3 7]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

print(np.vstack([x, grid]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [ ]:
#fonctions universelles :
# Il y a tout d'abord des opération mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arrondi

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [ ]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [ ]:
#opérations booléennes
x = np.random.rand(3,3)
x > 0.5

array([[False, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [ ]:
#retourne les index des éléments du tableau qui respecte la propriété
np.where(x > 0.5)


(array([0, 1, 2, 2]), array([2, 1, 0, 2]))

In [ ]:
L = np.random.random(100)
np.sum(L)


53.848485199679146

In [ ]:
#fonctions d'aggrégation 
M = np.random.random((3, 4))
print(M)
# Notez la syntax variable.fonction au lieu de 
# np.fonction(variable). Les deux sont possibles si
# la variable est un tableau Numpy.
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=0))

[[0.65966841 0.53320625 0.23053302 0.39486929]
 [0.61880856 0.47486752 0.47013219 0.71607453]
 [0.287991   0.38346223 0.74916984 0.87845219]]
La somme de tous les éléments de M:  6.397235040254322
Les sommes des colonnes de M:  [1.56646798 1.39153599 1.44983505 1.98939601]


In [ ]:
# np.std  pour calculer l'écart type
# np.argmin  pour trouver l'index de l'élément minimum
# np.percentile  pour calculer des statistiques sur les éléments.

#Broadcasting 
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + 5 # equivaut à a + b

array([5, 6, 7])

In [ ]:
M = np.ones((3, 3))
print("M vaut: \n", M)
print("M+a vaut: \n", M+a)

M vaut: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
M+a vaut: 
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
